# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
---
services:
  redis:
    deploy:
      resources:
        limits:
          cpus: "0"
          memory: "0"
    image: "redis:7.0.5-alpine"
    restart: "unless-stopped"
    stop_grace_period: "3s"
    volumes:
      - "redis:/data"
    profiles: [ "redis" ]

volumes:
  redis: { }
