# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
apiVersion: v1
kind: Namespace
metadata:
  name: crank
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: crank
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: crank
  labels:
    app: redis
    role: slave
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: slave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: crank
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis
        image: redis:7.0.5-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: crank
  labels:
    app: redis
    role: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: redis:7.0.5-alpine
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: "redis-master"
        - name: REDIS_REPLICATION_MODE
          value: "slave"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"