# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
"""
Django settings for crank project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import multiprocessing
import os
from pathlib import Path

from dotenv import load_dotenv
from newrelic import agent
from opentelemetry.instrumentation.django import DjangoInstrumentor
from opentelemetry.instrumentation.redis import RedisInstrumentor

load_dotenv()
DjangoInstrumentor().instrument(is_sql_commentor_enabled=True)
RedisInstrumentor().instrument()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
CONTENT_DIR = os.path.join(str(BASE_DIR), "crank/content")
DEFAULT_ALGORITHM_ID = 5
DEBUG = False

LOGGING = {
    'version': 1,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'django': {
            'level': 'INFO',
            'handlers': ['console'],
        },
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'crank',
    'django_bootstrap5',
    'django_extensions',
    'fontawesomefree',
    'corsheaders',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'whitenoise',
    'manifest_loader'
]

if DEBUG:
    INSTALLED_APPS += (
        'coverage',
        'debug_toolbar',
    )

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'crank.urls'

SECURE_CROSS_ORIGIN_OPENER_POLICY = None
CORS_ALLOWED_ORIGINS = [
    "http://local.crank.fyi",
    "http://local.crank.fyi:8000",
    "http://staging.crank.fyi",
    "https://www.crank.fyi",
    "https://crank.fyi",
    "https://cloudflareinsights.com",
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://local.crank.fyi",
    "http://staging.crank.fyi",
    "https://www.crank.fyi",
    "https://crank.fyi",
]
CSRF_COOKIE_DOMAIN = ".crank.fyi"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crank.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS = 1000

# Use the database (not Redis) for sessions. django-allauth stashes the OAuth
# state into the session between /accounts/google/login/ and the callback at
# /accounts/google/login/callback/; if Redis evicts that key under memory
# pressure, allauth can't verify state and renders "Third-Party Login Failure".
# The shared Redis master is a single 256Mi replica with no persistence, so
# keep sessions on the durable MySQL store instead.
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_DOMAIN = ".crank.fyi"
SESSION_COOKIE_SECURE = False
# Set session timeout to 30 minutes
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds

CACHE_MIDDLEWARE_SECONDS = int(os.environ.get("CACHE_TTL", "60"))  # Timeout for cached items in seconds

# Job-search chat transport limits (Phase 1). Tokens/settings only; no secrets.
JOB_SEARCH_MESSAGE_MAX_LEN = int(os.environ.get("JOB_SEARCH_MESSAGE_MAX_LEN", "4000"))
JOB_SEARCH_RESPONSE_MAX_LEN = int(os.environ.get("JOB_SEARCH_RESPONSE_MAX_LEN", "8000"))
JOB_SEARCH_REQUEST_MAX_BYTES = int(os.environ.get("JOB_SEARCH_REQUEST_MAX_BYTES", "65536"))
JOB_SEARCH_MESSAGES_RETENTION = int(os.environ.get("JOB_SEARCH_MESSAGES_RETENTION", "50"))
JOB_SEARCH_RATE_LIMIT_PER_HOUR = int(os.environ.get("JOB_SEARCH_RATE_LIMIT_PER_HOUR", "120"))
JOB_SEARCH_PROVIDER = os.environ.get("JOB_SEARCH_PROVIDER", "demo")
REDIS_MASTER_URL = os.environ.get("REDIS_MASTER_URL", "redis://redis-master:6379/0")

# Phase 2 score normalization/resolution pipeline (issue #313).
# Curated policy only; never read from untrusted external payloads. Empty by
# default so production is inert until an operator declares a rating source.
# All numeric/string limits are implemented as reject-not-clamp and bound
# untrusted text. No secrets live here.
SCORE_RESOLUTION_VERSION = os.environ.get("SCORE_RESOLUTION_VERSION", "1")
SCORE_RESOLUTION_SOURCE_KEY = os.environ.get("SCORE_RESOLUTION_SOURCE_KEY", "default")
# Organization.name (verbatim) of the rating source organization.
RATING_SOURCE_ORGANIZATION_NAME = os.environ.get("RATING_SOURCE_ORGANIZATION_NAME", "")
# Curated external score-type mappings: list of
# {"source": key, "external": external token, "score_type": ScoreType.name}.
SCORE_TYPE_MAPPINGS = []  # declared in deploy config, not in source defaults
# Curated target aliases: list of
# {"kind": "external_id"|"domain"|"name", "alias": token, "organization": Organization.name}.
SCORE_TARGET_ALIASES = []
SCORE_MAX_VALUE_MAGNITUDE = os.environ.get("SCORE_MAX_VALUE_MAGNITUDE", "1e15")
SCORE_MAX_DECIMAL_SIGNIFICANT_DIGITS = int(
    os.environ.get("SCORE_MAX_DECIMAL_SIGNIFICANT_DIGITS", "30"))
SCORE_MAX_STRING_LENGTH = int(os.environ.get("SCORE_MAX_STRING_LENGTH", "512"))
SCORE_MAX_OBSERVATIONS = int(os.environ.get("SCORE_MAX_OBSERVATIONS", "100000"))

# Optional: To use Redis for session storage
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_MASTER_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,  # in seconds
            'SOCKET_TIMEOUT': 5,  # in seconds
        }
    }
}

# Set the TTL for session entries in Redis
SESSION_REDIS = {
    'ttl': 1800,  # 30 minutes in seconds
    'master': REDIS_MASTER_URL,
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Log the underlying exception behind allauth's stock "Third-Party Login
# Failure" page instead of swallowing it.
SOCIALACCOUNT_ADAPTER = 'crank.adapters.SocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/dist"),
]
MANIFEST_LOADER = {
    "BACKEND": "manifest_loader.loader.ManifestLoader",
    "MANIFEST_PATH": os.path.join(BASE_DIR, "static/dist/manifest.json"),
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# LLM provider gateway
# ---------------------------------------------------------------------------
# Environment-backed, FAIL-CLOSED settings for the typed LLM gateway in
# crank/agents/llm.py. Reading an API key is the ONLY secret here; it is read
# exclusively from the environment (never from checked-in code) and defaults
# to empty so any provider that requires one refuses to start when unset.
#
# LLM_PROVIDER selects the single provider implementation; the offline
# FakeLLMProvider is a safe default that makes no network calls. Deploying a
# live provider requires opting in via env with its key/model configured.

# Which provider class to use. Empty => build the gateway fails closed.
LLM_PROVIDER = os.environ.get("LLM_PROVIDER", "").strip()
# Model identifier. Required (and validated) only by providers that need it.
LLM_MODEL = os.environ.get("LLM_MODEL", "").strip()
# API key for provider SDK calls. SECRET: environment-linked, no default.
LLM_API_KEY = os.environ.get("LLM_API_KEY", "").strip()
# Request timeout in seconds, forwarded to provider adapters.
LLM_TIMEOUT_SECONDS = float(os.environ.get("LLM_TIMEOUT_SECONDS", "30"))
# Per-request token ceiling, enforced before any request is sent.
LLM_MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "2048"))
# Per-user spend ceiling in USD (0 disables the guard).
LLM_PER_USER_COST_LIMIT_USD = float(os.environ.get("LLM_PER_USER_COST_LIMIT_USD", "0"))
# Optional price (USD per 1k total tokens) used to estimate cost.
LLM_PRICE_PER_1K_TOKENS_USD = float(os.environ.get("LLM_PRICE_PER_1K_TOKENS_USD", "0"))
# Independent feature flag for the interactive job-search agent. Disabling this
# does NOT affect scheduled ingestion, which has its own lifecycle controls.
INTERACTIVE_AGENT_ENABLED = os.environ.get("INTERACTIVE_AGENT_ENABLED", "false").lower() in (
    "1", "true", "yes", "on"
)

def _env_bool(name, default=False):
    """Parse a boolean environment variable, defaulting when unset."""
    return os.environ.get(name, "1" if default else "0").strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    )


def _env_int(name, default):
    """Parse an integer environment variable, defaulting when unset/invalid."""
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


def _env_float(name, default):
    """Parse a float environment variable, defaulting when unset/invalid."""
    try:
        return float(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


# Scheduled agent runs (roadmap: docs/readme.md section 8.1). Disabled by
# default until secrets and policies are ready; operators enable them per
# environment. These flags gate whether the management commands may claim a run.
AGENT_RUN_ENABLED = _env_bool("AGENT_RUN_ENABLED")
# Per-command flag for the reference no-op run.
AGENT_NOOP_ENABLED = _env_bool("AGENT_NOOP_ENABLED")
# Staleness TTL (seconds): a RUNNING claim older than this is treated as a
# crashed/stale lock and reclaimed by the next claim for the same run type.
AGENT_RUN_STALE_AFTER_SECONDS = _env_int("AGENT_RUN_STALE_AFTER_SECONDS", 3600)

# Yelp Fusion source adapter (roadmap: docs/readme.md 8.2, phase 2). The name
# ``YELP_API_KEY`` is read as a secret from the environment only; it is never
# committed and never logged. The other knobs tune the hardened transport.
# Leave the key unset in dev/CI so the adapter fails closed.
YELP_API_KEY = os.environ.get("YELP_API_KEY", "").strip()
YELP_BASE_URL = os.environ.get("YELP_BASE_URL", "https://api.yelp.com/v3").strip()
YELP_CONNECT_TIMEOUT = _env_float("YELP_CONNECT_TIMEOUT", 3.05)
YELP_READ_TIMEOUT = _env_float("YELP_READ_TIMEOUT", 30)
YELP_MAX_REDIRECTS = _env_int("YELP_MAX_REDIRECTS", 5)
YELP_MAX_BYTES = _env_int("YELP_MAX_BYTES", 2 * 1024 * 1024)
YELP_MAX_TRANSIENT_ATTEMPTS = _env_int("YELP_MAX_TRANSIENT_ATTEMPTS", 4)
