# Generated by Django 4.2.6 on 2023-10-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='C', max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('gives_ratings', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAlgorithmWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crank.scorealgorithm')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crank.scoretype')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('low_threshold', models.FloatField(default=0.0)),
                ('high_threshold', models.FloatField(default=5.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='source_organization', to='crank.organization')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='target_organization', to='crank.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crank.organizationtype'),
        ),
    ]
