# Generated by Django 4.2.6 on 2023-10-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtype',
            name='gives_ratings',
        ),
        migrations.AddField(
            model_name='organization',
            name='gives_ratings',
            field=models.BooleanField(default=False),
        ),
    ]
