# Generated by Django 4.2.6 on 2023-11-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='crank.organization'),
        ),
    ]
