# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 4.2.6 on 2023-11-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0002_alter_score_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='source',
            field=models.ForeignKey(limit_choices_to={'gives_ratings': 1, 'status': 1}, on_delete=django.db.models.deletion.RESTRICT, related_name='scores_given', to='crank.organization'),
        ),
        migrations.AlterField(
            model_name='score',
            name='type',
            field=models.ForeignKey(default=None, limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='crank.scoretype'),
        ),
        migrations.AlterField(
            model_name='scorealgorithmweight',
            name='type',
            field=models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='crank.scoretype'),
        ),
    ]
