# Generated by Django 4.2.6 on 2023-10-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0002_remove_organizationtype_gives_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
