# Generated by Django 4.2.6 on 2023-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0003_organization_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorealgorithm',
            name='description_content',
            field=models.CharField(default='', max_length=50),
        ),
    ]
