# Generated by Django 4.2.6 on 2023-10-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0004_scorealgorithm_description_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoreAlgorithmWeights',
            new_name='ScoreAlgorithmWeight',
        ),
    ]
