# Generated by Django 4.2.6 on 2023-10-31 22:12

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0005_rename_scorealgorithmweights_scorealgorithmweight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='scorealgorithm',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='scorealgorithmweight',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='scoretype',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='organization',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='score',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='scorealgorithm',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='scorealgorithm',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorealgorithm',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='scorealgorithm',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='scorealgorithm',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='scorealgorithmweight',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='scorealgorithmweight',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorealgorithmweight',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='scorealgorithmweight',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='scorealgorithmweight',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='activate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoretype',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status'),
        ),
    ]
