# Generated by Django 4.2.14 on 2024-08-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0005_alter_scorealgorithmweight_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scorealgorithm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scoretype',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='accelerated_vesting',
            field=models.BooleanField(default=False),
        ),
    ]
