# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 5.0.14 on 2026-08-07 02:11

import crank.models.preference
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0006_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('status', models.CharField(choices=[('A', 'Active'), ('R', 'Archived')], default='A', max_length=1, verbose_name='status')),
                ('retention_until', models.DateTimeField(blank=True, help_text='Retain the conversation until this timestamp; NULL keeps it until it is archived or the owning user is deleted.', null=True, verbose_name='retention until')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('role', models.CharField(choices=[('U', 'User'), ('A', 'Assistant')], max_length=1, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('status', models.CharField(choices=[('S', 'Sent'), ('E', 'Error')], default='S', max_length=1, verbose_name='status')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crank.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('preferences', models.JSONField(default=crank.models.preference.default_preferences, help_text='Versioned canonical preference document. Server-controlled source of truth.', verbose_name='preferences')),
                ('preferences_markdown', models.TextField(blank=True, default='', help_text='Server-generated markdown projection of the canonical preferences.', verbose_name='preferences markdown')),
                ('schema_version', models.PositiveIntegerField(default=1, help_text='Version of the preferences JSON document schema.', verbose_name='schema version')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user preference',
                'verbose_name_plural': 'user preferences',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-modified'], name='crank_conv_user_modified_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status'], name='crank_conv_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'order'], name='crank_msg_conv_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'order'), name='crank_message_unique_conv_order', violation_error_message='Each message must have a unique order within its conversation.'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user'], name='crank_userpref_user_idx'),
        ),
    ]
