# Generated by Django 4.2.6 on 2023-11-02 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0006_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crank.scoretype'),
        ),
    ]
