# Generated by Django 4.2.6 on 2023-11-05 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0007_score_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='funding_round',
            field=models.CharField(choices=[('S', 'Seed'), ('A', 'Series A'), ('B', 'Series B'), ('C', 'Series C'), ('D', 'Series D'), ('E', 'Series E'), ('F', 'Series F'), ('X', 'Series G or Later'), ('O', 'Other Private'), ('P', 'Public')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='rto_policy',
            field=models.CharField(choices=[('R', 'Remote'), ('H', 'Hybrid'), ('O', 'In-Office')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scores_given', to='crank.organization'),
        ),
        migrations.AlterField(
            model_name='score',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scores_received', to='crank.organization'),
        ),
    ]
