# Generated by Django 6.1 on 2026-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0010_jobsearchconversation_jobsearchmessage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobsearchmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('conversation', 'idempotency_key', 'role'), name='unique_jobsearch_message_idempotency'),
        ),
    ]
