# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0011_jobsearch_idempotency_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='score',
            name='run',
            field=models.ForeignKey(blank=True, help_text='Run that produced this observation, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='crank.agentrun'),
        ),
    ]
