# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-07 16:43

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0011_jobsearch_idempotency_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('adapter_key', models.CharField(db_index=True, help_text='Identifier of the code-registered adapter implementation.', max_length=64, verbose_name='adapter key')),
                ('base_url', models.URLField(help_text='HTTPS base URL on a code-owned allowlisted domain (SSRF guard).', max_length=512, verbose_name='base URL')),
                ('approval_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=16, verbose_name='approval state')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cadence', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=16, verbose_name='request cadence')),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('max_response_bytes', models.PositiveIntegerField(default=1048576)),
                ('terms_reviewed', models.BooleanField(default=False)),
                ('terms_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(limit_choices_to={'gives_ratings': True, 'status': 1}, on_delete=django.db.models.deletion.RESTRICT, related_name='source_catalog', to='crank.organization', verbose_name='rating organization')),
                ('supported_score_types', models.ManyToManyField(blank=True, related_name='sources', to='crank.scoretype', verbose_name='supported score types')),
            ],
            options={
                'verbose_name': 'source catalog',
                'verbose_name_plural': 'source catalog',
            },
        ),
        migrations.CreateModel(
            name='SourceCatalogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('action', models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('approved', 'Approved'), ('blocked', 'Blocked'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], db_index=True, max_length=16)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='crank.sourcecatalog', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_catalog_audits', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'source catalog audit',
                'verbose_name_plural': 'source catalog audits',
            },
        ),
        migrations.CreateModel(
            name='SourceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped (another run is active)')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('adapter_version', models.CharField(blank=True, default='', max_length=32)),
                ('counts', models.JSONField(blank=True, default=dict, verbose_name='counts')),
                ('error_summary', models.TextField(blank=True, default='', verbose_name='error summary')),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crank.agentrun', verbose_name='agent run')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='runs', to='crank.sourcecatalog', verbose_name='source')),
            ],
            options={
                'verbose_name': 'source run',
                'verbose_name_plural': 'source runs',
            },
        ),
        migrations.AddIndex(
            model_name='sourcecatalog',
            index=models.Index(fields=['adapter_key'], name='crank_source_adptkey_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcecatalog',
            index=models.Index(fields=['approval_state'], name='crank_source_approval_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcerun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('source', 'status'), name='unique_source_run_running_per_source', violation_error_message='A source run for this source is already running.'),
        ),
    ]
