# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-11 06:46

import django.db.models.deletion
import django.db.models.manager
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0013_alter_agentrun_run_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSourceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('adapter_key', models.CharField(db_index=True, max_length=64)),
                ('base_url', models.URLField(max_length=1024)),
                ('approval_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=16)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('catalog_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'job source catalog',
                'verbose_name_plural': 'job source catalog',
                'indexes': [models.Index(fields=['adapter_key'], name='crank_jobsrc_adptkey_idx'), models.Index(fields=['approval_state', 'enabled'], name='crank_jobsrc_policy_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('external_id', models.CharField(blank=True, default='', max_length=256)),
                ('canonical_url', models.URLField(max_length=1024)),
                ('employer_name', models.CharField(max_length=200)),
                ('employer_domain', models.CharField(blank=True, default='', max_length=253)),
                ('title', models.CharField(max_length=300)),
                ('location_text', models.CharField(blank=True, default='', max_length=500)),
                ('is_remote', models.BooleanField(default=False)),
                ('compensation_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('compensation_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('compensation_currency', models.CharField(blank=True, default='', max_length=3)),
                ('compensation_interval', models.CharField(blank=True, default='', max_length=32)),
                ('description_excerpt', models.TextField(blank=True, default='', max_length=2000)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='active', max_length=8)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='crank.jobsourcecatalog')),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['source', 'status', 'last_seen_at'], name='crank_joblist_fresh_idx'), models.Index(fields=['employer_domain', 'status'], name='crank_joblist_employer_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_job_source_external_id'), models.UniqueConstraint(fields=('source', 'canonical_url'), name='unique_job_source_canonical_url')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
