# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-11 07:09

import crank.agents.jobs.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0014_jobsourcecatalog_joblisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsourcecatalog',
            name='catalog_metadata',
            field=models.JSONField(blank=True, default=dict, validators=[crank.agents.jobs.base.validate_catalog_metadata]),
        ),
    ]
