# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-12 02:29

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0015_alter_jobsourcecatalog_catalog_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='employer_external_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings', to='crank.organization'),
        ),
        migrations.CreateModel(
            name='EmployerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('kind', models.CharField(choices=[('external_id', 'External ID'), ('domain', 'Domain'), ('name', 'Normalized Name')], max_length=16)),
                ('value', models.CharField(max_length=253)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_aliases', to='crank.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employer_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'value', 'status'], name='crank_empr_alias_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='unique_employer_alias_kind_value')],
            },
        ),
        migrations.CreateModel(
            name='UnresolvedEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('employer_name', models.CharField(max_length=200)),
                ('employer_domain', models.CharField(blank=True, default='', max_length=253)),
                ('reason', models.CharField(choices=[('no_match', 'No Match'), ('ambiguous', 'Ambiguous'), ('inactive', 'Inactive Organization'), ('not_public', 'Not Public Organization')], max_length=16)),
                ('candidates', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_employers', to='crank.joblisting')),
            ],
            options={
                'indexes': [models.Index(fields=['reason', 'resolved'], name='crank_unres_employer_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved', False)), fields=('listing',), name='unique_open_unresolved_employer_listing')],
            },
        ),
    ]
