# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-12 04:10

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0016_joblisting_employer_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('preference_version', models.PositiveIntegerField()),
                ('ranker_version', models.CharField(max_length=32)),
                ('score', models.FloatField()),
                ('factors', models.JSONField(blank=True, default=list)),
                ('first_matched_at', models.DateTimeField()),
                ('last_matched_at', models.DateTimeField()),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(db_index=True, default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='crank.joblisting')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_matches', to='crank.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'id'],
                'indexes': [models.Index(fields=['user', 'dismissed', '-score'], name='crank_jobmatch_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing', 'preference_version', 'ranker_version'), name='unique_job_match_version')],
            },
        ),
    ]
