# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crank", "0017_jobmatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="run_type",
            field=models.CharField(
                choices=[
                    ("noop", "No-op reference run"),
                    ("gather_scores", "Score gathering run"),
                    ("job_pipeline", "Job pipeline run"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
