# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-12 21:42

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0019_monitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfileObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_url', models.URLField(max_length=750)),
                ('observed_domain', models.CharField(blank=True, db_index=True, default='', max_length=253)),
                ('observed_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('locations', models.JSONField(blank=True, default=list)),
                ('rto_evidence', models.TextField(blank=True, default='')),
                ('funding_evidence', models.TextField(blank=True, default='')),
                ('public_status_evidence', models.TextField(blank=True, default='')),
                ('logo_url', models.URLField(blank=True, default='', max_length=750)),
                ('brand_metadata', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('extraction_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('auto_applied', 'Auto-applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('conflicted', 'Conflicted')], db_index=True, default='pending', max_length=16)),
                ('conflict_fields', models.JSONField(blank=True, default=list)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profile_observations', to='crank.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_company_profile_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['observed_domain', 'status'], name='crank_cpo_domain_status_idx'), models.Index(fields=['source_url', 'observed_at'], name='crank_cpo_source_time_idx')],
            },
        ),
    ]
