# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-12 22:06

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0022_alter_agentrun_run_type'),
        ('crank', '0021_companyrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='run_type',
            field=models.CharField(choices=[('noop', 'No-op reference run'), ('gather_scores', 'Score gathering run'), ('job_pipeline', 'Job pipeline run'), ('crawl_schedule', 'Crawl scheduling run'), ('crawl', 'On-demand crawl run')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_type', models.CharField(choices=[('organization', 'Organization'), ('job', 'Job')], db_index=True, max_length=16)),
                ('source_key', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=16)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_runs', to='crank.agentrun')),
                ('job_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='crawl_runs', to='crank.jobsourcecatalog')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_crawl_runs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='crawl_runs', to='crank.sourcecatalog')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'source_key', 'started_at'], name='crank_crawl_source_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('outcome', 'running')), fields=('source_type', 'source_key', 'outcome'), name='unique_crawl_running_per_source')],
            },
        ),
    ]
