# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0024_preference_schema_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='schema_version',
            field=models.PositiveIntegerField(default=2, help_text='Version of the preferences JSON document schema.', verbose_name='schema version'),
        ),
        migrations.AlterField(
            model_name='userpreferenceaudit',
            name='schema_version',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
