# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0026_jobsearchmessage_results_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRetrievalOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Job Retrieval Operations',
                'verbose_name_plural': 'Job Retrieval Operations',
                'managed': False,
            },
        ),
    ]
