# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0027_jobretrievalops'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentrun',
            name='unique_agentrun_running_per_type',
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['running', 'pending'])), fields=('run_type', 'status'), name='unique_agentrun_active_per_type', violation_error_message='An agent run of this type is already active (running or pending); this invocation should be recorded as skipped.'),
        ),
    ]
