# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-08-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0028_jobsearchconversation_helpfulness_gap_emitted'),
        ('crank', '0028_remove_agentrun_unique_agentrun_running_per_type_and_more'),
    ]

    operations = [
    ]
