# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-09-15 07:57
# Numbered 0031 per the recorded controller resolution (0030 = #458
# jobsearch_turn_state, 0032 = #461 score_tuple_anchor). Dependency must be
# updated to the then-latest landed head at merge time; see
# docs/deployment-migrations.md.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0029_merge_20260815_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('organization', 'Organization'), ('score', 'Score'), ('listing', 'Listing')], max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('event_kind', models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('observed', 'Observed'), ('ingested', 'Ingested')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['processed_at', 'id'], name='crank_pubevent_sweep_idx')],
            },
        ),
    ]
