# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-09-15 05:27

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0029_merge_20260815_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTupleAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_tuple_anchors_given', to='crank.organization')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_tuple_anchors_received', to='crank.organization')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_tuple_anchors', to='crank.scoretype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'source', 'target'), name='unique_score_tuple_anchor', violation_error_message='There is already an anchor for this score tuple')],
            },
        ),
    ]
