# Generated by Django 6.1 on 2026-09-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0031_publicationevent'),
        ('crank', '0033_merge_20260915_0828'),
    ]

    operations = [
    ]
