# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 6.1 on 2026-09-20 23:53

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0035_preference_schema_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFieldEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('field_key', models.CharField(choices=[('rto_policy', 'RTO policy'), ('funding_round', 'Funding round'), ('public_status', 'Public status'), ('accelerated_vesting', 'Accelerated vesting'), ('locations', 'Locations'), ('company_name', 'Company name'), ('company_domain', 'Company domain')], db_index=True, max_length=32)),
                ('value_text', models.CharField(blank=True, default='', max_length=500)),
                ('source_url', models.URLField(max_length=750)),
                ('source_domain', models.CharField(blank=True, db_index=True, default='', max_length=253)),
                ('scope_json', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('validation_version', models.CharField(max_length=64)),
                ('extractor_version', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('accepted', 'Accepted'), ('superseded', 'Superseded'), ('conflicted', 'Conflicted')], db_index=True, default='accepted', max_length=16)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_evidence', to='crank.companyprofileobservation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_evidence', to='crank.organization')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'field_key', 'state'], name='crank_cfe_org_field_state_idx')],
            },
        ),
    ]
