# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
# Generated by Django 5.0.14 on 2026-09-29 23:06

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0046_alter_companyfieldevidence_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('field_key', models.CharField(choices=[('rto_policy', 'RTO policy'), ('funding_round', 'Funding round'), ('public_status', 'Public status'), ('accelerated_vesting', 'Accelerated vesting'), ('locations', 'Locations'), ('company_name', 'Company name'), ('company_domain', 'Company domain')], max_length=32)),
                ('current_value', models.CharField(blank=True, default='', max_length=500)),
                ('proposed_value', models.CharField(max_length=500)),
                ('evidence_url', models.URLField(max_length=750)),
                ('scope_level', models.CharField(choices=[('company', 'Company'), ('team', 'Team'), ('role', 'Role'), ('location', 'Location')], default='company', max_length=16)),
                ('scope_value', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='pending', max_length=16)),
                ('admin_note', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField()),
                ('current_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='crank.companyfieldevidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='crank.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_corrections', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_company_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-id'],
                'indexes': [models.Index(fields=['organization', 'field_key', 'status'], name='crank_cc_org_field_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('requester', 'idempotency_key'), name='unique_company_correction_idempotency')],
            },
        ),
    ]
