# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
name: Check License Headers

on:
  push:
    paths-ignore:
      - 'crank/migrations/**'
      - 'seeds/**'
      - 'dump/**'
      - '.gitignore'

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Check for license headers
        run: |
          python check_license.py