# Copyright (c) 2024 Isaac Adams
# Licensed under the MIT License. See LICENSE file in the project root for full license information.
name: Deploy to Kubernetes on Fats
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [ "Build Image" ]
    types:
      - completed

jobs:
  deploy-home-k3s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Cloudflared
        run: |
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

          # Add this repo to your apt repositories
          # echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          # this workaround is necessary because cloudflared 2024.10.1 is broken
          curl -O https://github.com/cloudflare/cloudflared/releases/download/2024.10.0/cloudflared-linux-arm.deb
          sudo apt install ./cloudflared-linux-arm.deb

          # install cloudflared
          sudo apt-get update && sudo apt-get install cloudflared=2024.10.0

      - name: Deploy to Kubernetes
        run: |
          # Copy deployment.yml to the remote system
          scp -o ProxyCommand='cloudflared access ssh --hostname %h' -o StrictHostKeyChecking=no ./k8s/deployment.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/deployment.yml

          # Apply the copied deployment.yml
          ssh -o ProxyCommand='cloudflared access ssh --hostname %h' -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          export GITHUB_SHA=${{ github.sha }}
          envsubst < /tmp/deployment.yml | k3s kubectl apply -f -
          EOF