name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Install PlanetScale CLI
      run: |
        curl -L https://github.com/planetscale/cli/releases/latest/download/pscale-cli-linux-amd64 -o pscale
        chmod +x pscale
        sudo mv pscale /usr/local/bin/

    - name: Log in to PlanetScale
      run: |
        echo ${{ secrets.PSCALE_TOKEN }} | pscale auth login

    - name: Connect to PlanetScale database
      run: |
        pscale connect my-database main

    - name: Deploy to Google Cloud
      run: |
        gcloud app deploy