name: Run Tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          ENV: dev
          SECRET_KEY: '${{ secrets.SECRET_KEY }}'
        run: |
          pytest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Run webpack
        run: npx webpack

      - name: Run Jest tests
        run: npx jest