name: Update latest label

on:
  push:
    branches:
      - main

jobs:
  update-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest package version
        id: latest-version
        run: |
          JSON_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/packages/container/crank/versions)
          if [ $(echo $JSON_RESPONSE | jq '. | length') -gt 0 ] && [ $(echo $JSON_RESPONSE | jq '.[0].metadata.container.tags | length') -gt 0 ]; then
            VERSION=$(echo $JSON_RESPONSE | jq -r '.[0].metadata.container.tags[0]')
            echo "::set-output name=version::$VERSION"
          fi

      - name: Update latest label
        run: |
          if [ -n "${{ steps.latest-version.outputs.version }}" ]; then
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/packages/container/crank/versions/${{ steps.latest-version.outputs.version }}/labels -d '{"labels": ["latest"]}'
          fi